POST http://localhost:3001/api/blogs
Content-Type: Application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjVhODM2MjVlMWMzOTJmMzU5NjI4MmIxYyIsImlhdCI6MTUxODYxMzkwM30.qd3Img4uYQRBGsOXhBx5E-8H6KcgIas-ItX4Ds9IQtI

{
    "title": "title2",
    "author": "author2 here",
    "url": "url here",
    "likes": 1
}