POST http://localhost:3003/api/blogs
Content-Type: Application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjVhODgzNjE2ZmMxOGY0MGMzMzZhNDc4MiIsImlhdCI6MTUyMDA5Nzk2MH0.YE08tvvAlhJwcAxBPF5OtGfD8sbjFi1-utN8ZffvH1s

{
    "title": "title2",
    "author": "author2 here",
    "url": "url here",
    "likes": 1
}